variables:
 - name: project_name
   value: Maya-Commander
 - name: esp_project_name
   value: esp-8266-device

trigger:
  branches:
    include:
    - '*'
    exclude:
    - artifacts

stages:
 - stage: ESP8266_device
   
   dependsOn: [] #build
   
   jobs:
    - job: build
      strategy:
        matrix:
          ubuntu_22_04:
            os_image: 'ubuntu-22.04'
            agent_pool: 'Azure Pipelines'
      pool:
        vmImage: $(os_image)
        name: $(agent_pool)
      
      condition: true
      timeoutInMinutes: 50
      steps:
       - script: ls /usr/lib/jvm/
         displayName: "check Java install directory"
         condition: succeeded()

 - stage: Maya_Commander
   
   dependsOn: [] #build
   
   jobs:
    - job: analyze_multiple_json_configs
      strategy:
        matrix:
          ubuntu_20_04:
            os_image: 'ubuntu-20.04'
            agent_pool: 'Azure Pipelines'
      pool:
        vmImage: $(os_image)
        name: $(agent_pool)
      condition: eq(variables['Build.Reason'], 'IndividualCI')
      timeoutInMinutes: 180
      steps:      
       - script: ls -la
         displayName: "test"
         condition: and(succeeded(), ne( variables['Agent.OS'], 'Windows_NT'))         
         