variables:
 - name: project_name
   value: Maya-Commander
 - name: esp_project_name
   value: esp-8266-device

trigger:
  branches:
    include:
    - '*'
    exclude:
    - artifacts

stages:
 - stage: ESP8266_device
   
   dependsOn: [] #build
   
   jobs:
    - job: build
      strategy:
        matrix:
          ubuntu_22_04:
            os_image: 'ubuntu-22.04'
            agent_pool: 'Azure Pipelines'
      pool:
        vmImage: $(os_image)
        name: $(agent_pool)
      
      condition: true
      timeoutInMinutes: 50
      steps:
       - script: sudo apt-get install gcc git wget make libncurses-dev flex bison gperf python-is-python3 python3-serial
         displayName: "Install the required packages for $(esp_project_name)"
         condition: succeeded()
       - script: ls -la
         displayName: "ls -la"
         condition: succeeded()
       - script: wget -O xtensa-lx106-elf-gcc8_4_0-esp-2020r3-linux-amd64.tar.gz https://dl.espressif.com/dl/xtensa-lx106-elf-gcc8_4_0-esp-2020r3-linux-amd64.tar.gz
         displayName: "Download xtensa-elf-gcc for linux amd64"
         condition: succeeded()
       - script: ls -la
         displayName: "ls -la"
         condition: succeeded()
       - script: |
          mkdir -p esp
          cd esp
          tar -xzf ../xtensa-lx106-elf-gcc8_4_0-esp-2020r3-linux-amd64.tar.gz
         displayName: "Unpack tar.gz archive"
         condition: succeeded()
       - script: ls -la esp/xtensa*/bin
         displayName: "ls -la esp/xtensa*/bin"
         condition: succeeded()
       - script: export PATH="$PATH:/home/vsts/work/_temp/esp/xtensa-lx106-elf/bin"
         displayName: "path var"
         condition: succeeded()
       - script: ls /home/vsts/work/_temp/esp/xtensa-lx106-elf/bin /home/vsts/work/_temp/esp/xtensa-lx106-elf /home/vsts/work/_temp/esp /home/vsts/work/_temp /home/vsts/work /home/vsts /home
         displayName: "ls /home/vsts/work/esp/xtensa-lx106-elf/bin"
         condition: succeeded()
       - script: pwd
         displayName: "ls .. .. .."
         condition: true
       - script: echo $PATH
         displayName: "check path var"
         condition: succeeded()
       - script: xtensa-lx106-elf-c++ --version
         displayName: "check path var"
         condition: succeeded()
       - script: | 
          export PATH="$PATH:/home/vsts/work/1/s/esp/xtensa-lx106-elf/bin"
          echo $PATH
          xtensa-lx106-elf-c++ --version
         displayName: "check path var"
         condition: true
       - script: xtensa-lx106-elf-c++ --version
         displayName: "Check xtensa available"
         condition: true
       - script: git submodule update --init --recursive
         displayName: "Init Git Submodules"
         condition: succeeded()
      # - script: cd maya && cmake -S . -B ./build/
      #   displayName: "CMake: Create Project"
      #   condition: succeeded()
      # - script: cd maya/script && cb-cmd-build.bat
      #   displayName: "CMake: Compile and Link (windows)"
      #   condition: and(succeeded(), eq( variables['Agent.OS'], 'Windows_NT' ))
      # - script: cd maya/script && ./ub-unix-build.sh 
      #   displayName: "CMake: Compile and Link (unix)"
      #   condition: and(succeeded(), ne( variables['Agent.OS'], 'Windows_NT' ))
      # - script: cd maya && ./build/test/TEST-$(project_name)
      #   displayName: "Run Tests on Linux / Mac OS"
      #   condition: and(succeeded(), ne( variables['Agent.OS'], 'Windows_NT'))
      # - script: dir maya\build\Debug\ && cd maya && .\build\Debug\TEST-$(project_name).exe
      #   displayName: "Run Tests on Windows"
      #   condition: and(succeeded(), eq( variables['Agent.OS'], 'Windows_NT' ))

 - stage: Maya_Commander
   
   dependsOn: [] #build
   
   jobs:
    - job: analyze_multiple_json_configs
      strategy:
        matrix:
          ubuntu_20_04:
            os_image: 'ubuntu-20.04'
            agent_pool: 'Azure Pipelines'
      pool:
        vmImage: $(os_image)
        name: $(agent_pool)
      condition: eq(variables['Build.Reason'], 'IndividualCI')
      timeoutInMinutes: 180
      steps:      
       - script: ls -la
         displayName: "test"
         condition: and(succeeded(), ne( variables['Agent.OS'], 'Windows_NT'))         
         