#include "config.h"

#ifdef VALVE_SERVER_JAMES



// JAMES_ESP_TO_ATM_SYNC
#define PIN_D1 5
#define JAMES_ESP_TO_ATM_SYNC PIN_D1

// JAMES_ESP_TO_ATM_CLOCK
#define PIN_D2 4
#define JAMES_ESP_TO_ATM_CLOCK PIN_D2

// JAMES_ESP_TO_ATM_DATA
#define PIN_D7 13
#define JAMES_ESP_TO_ATM_DATA PIN_D7

// JAMES_ATM_TO_ESP_DATA // blue LED on wifi board is on if pulled low.
#define PIN_D4 2
#define JAMES_ATM_TO_ESP_DATA PIN_D4

// JAMES_ATM_TO_ESP_CLOCK
#define PIN_D3 0
#define JAMES_ATM_TO_ESP_CLOCK PIN_D3



#define GPIO_INPUT_LANES ((1ULL<<JAMES_ATM_TO_ESP_DATA) | (1ULL<<JAMES_ATM_TO_ESP_CLOCK))

#define GPIO_OUTPUT_LANES ((1ULL<<JAMES_ESP_TO_ATM_DATA) | (1ULL<<JAMES_ESP_TO_ATM_CLOCK) | (1ULL<<JAMES_ESP_TO_ATM_SYNC))



#endif // VALVE_SERVER_JAMES


